service: ing-henry-portfolio-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    EMAIL_HOST: ${env:EMAIL_HOST}
    EMAIL_PORT: ${env:EMAIL_PORT}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_FROM: ${env:EMAIL_FROM}
    PAYSTACK_SECRET_KEY: ${env:PAYSTACK_SECRET_KEY}
    FRONTEND_URL: ${env:FRONTEND_URL, 'https://dhokabeatz.com'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
  serverless-offline:
    httpPort: 4000
    lambdaPort: 3002
    websocketPort: 3001
    host: localhost
    noPrependStageInUrl: true

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Requested-With
            allowCredentials: true

package:
  exclude:
    - node_modules/.prisma/client/libquery_engine-*
    - '!node_modules/.prisma/client/libquery_engine-rhel-*'
    - node_modules/@prisma/engines/**
    - 'src/**'
    - 'test/**'
    - 'logs/**'
    - '.env*'
    - 'README.md'
    - '.gitignore'
    - 'nest-cli.json'
    - 'tsconfig*.json'
  include:
    - dist/**
    - node_modules/.prisma/**
    - prisma/schema.prisma
