name: Deploy Frontend to AWS S3 + CloudFront

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: dhokabeatz-portfolio
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test -- --run

      - name: Build application
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_APP_NAME: "Ing. Henry Portfolio"
          VITE_NODE_ENV: production

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Upload static assets with long cache
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} \
            --delete \
            --cache-control "max-age=31536000" \
            --exclude "*" \
            --include "*.js" \
            --include "*.css" \
            --include "*.png" \
            --include "*.jpg" \
            --include "*.jpeg" \
            --include "*.gif" \
            --include "*.svg" \
            --include "*.ico" \
            --include "*.woff" \
            --include "*.woff2"

          # Upload HTML files with short cache
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} \
            --delete \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate" \
            --exclude "*" \
            --include "*.html"

          # Upload other files
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} \
            --delete \
            --exclude "*.js" \
            --exclude "*.css" \
            --exclude "*.png" \
            --exclude "*.jpg" \
            --exclude "*.jpeg" \
            --exclude "*.gif" \
            --exclude "*.svg" \
            --exclude "*.ico" \
            --exclude "*.woff" \
            --exclude "*.woff2" \
            --exclude "*.html"

      - name: Invalidate CloudFront
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.CLOUDFRONT_DISTRIBUTION_ID
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deploy summary
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "🚀 Frontend deployed successfully!"
          echo "📦 S3 Bucket: s3://${{ env.S3_BUCKET_NAME }}"
          echo "🌐 Website URL: https://dhokabeatz.com"
          if [ -n "${{ env.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            echo "🔄 CloudFront invalidation created"
          fi
